// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ufo/v1/ufo.proto

package ufo_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SightingInfo содержит данные о наблюдении.
type SightingInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Место наблюдения.
	Location string `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	// Описание наблюдения.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Имя наблюдателя.
	Observer string `protobuf:"bytes,3,opt,name=observer,proto3" json:"observer,omitempty"`
	// Подтверждено ли наблюдение.
	IsConfirmed   bool `protobuf:"varint,4,opt,name=is_confirmed,json=isConfirmed,proto3" json:"is_confirmed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SightingInfo) Reset() {
	*x = SightingInfo{}
	mi := &file_ufo_v1_ufo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SightingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SightingInfo) ProtoMessage() {}

func (x *SightingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ufo_v1_ufo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SightingInfo.ProtoReflect.Descriptor instead.
func (*SightingInfo) Descriptor() ([]byte, []int) {
	return file_ufo_v1_ufo_proto_rawDescGZIP(), []int{0}
}

func (x *SightingInfo) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *SightingInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SightingInfo) GetObserver() string {
	if x != nil {
		return x.Observer
	}
	return ""
}

func (x *SightingInfo) GetIsConfirmed() bool {
	if x != nil {
		return x.IsConfirmed
	}
	return false
}

// Sighting представляет полную запись наблюдения НЛО.
type Sighting struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Уникальный идентификатор наблюдения.
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// Данные о наблюдении.
	Info *SightingInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	// Время создания записи.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Время последнего обновления записи.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sighting) Reset() {
	*x = Sighting{}
	mi := &file_ufo_v1_ufo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sighting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sighting) ProtoMessage() {}

func (x *Sighting) ProtoReflect() protoreflect.Message {
	mi := &file_ufo_v1_ufo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sighting.ProtoReflect.Descriptor instead.
func (*Sighting) Descriptor() ([]byte, []int) {
	return file_ufo_v1_ufo_proto_rawDescGZIP(), []int{1}
}

func (x *Sighting) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Sighting) GetInfo() *SightingInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *Sighting) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Sighting) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// GetRequest запрос на получение наблюдения.
type GetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Уникальный идентификатор наблюдения.
	Uuid          string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_ufo_v1_ufo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ufo_v1_ufo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_ufo_v1_ufo_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// GetResponse ответ с данными наблюдения.
type GetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Данные наблюдения.
	Sighting      *Sighting `protobuf:"bytes,1,opt,name=sighting,proto3" json:"sighting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_ufo_v1_ufo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ufo_v1_ufo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_ufo_v1_ufo_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetSighting() *Sighting {
	if x != nil {
		return x.Sighting
	}
	return nil
}

var File_ufo_v1_ufo_proto protoreflect.FileDescriptor

const file_ufo_v1_ufo_proto_rawDesc = "" +
	"\n" +
	"\x10ufo/v1/ufo.proto\x12\x06ufo.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8b\x01\n" +
	"\fSightingInfo\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bobserver\x18\x03 \x01(\tR\bobserver\x12!\n" +
	"\fis_confirmed\x18\x04 \x01(\bR\visConfirmed\"\xbe\x01\n" +
	"\bSighting\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12(\n" +
	"\x04info\x18\x02 \x01(\v2\x14.ufo.v1.SightingInfoR\x04info\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\" \n" +
	"\n" +
	"GetRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\";\n" +
	"\vGetResponse\x12,\n" +
	"\bsighting\x18\x01 \x01(\v2\x10.ufo.v1.SightingR\bsighting2<\n" +
	"\n" +
	"UFOService\x12.\n" +
	"\x03Get\x12\x12.ufo.v1.GetRequest\x1a\x13.ufo.v1.GetResponseBKZIgithub.com/mbakhodurov/examples2/week_7/easy_logs/pkg/proto/ufo/v1;ufo_v1b\x06proto3"

var (
	file_ufo_v1_ufo_proto_rawDescOnce sync.Once
	file_ufo_v1_ufo_proto_rawDescData []byte
)

func file_ufo_v1_ufo_proto_rawDescGZIP() []byte {
	file_ufo_v1_ufo_proto_rawDescOnce.Do(func() {
		file_ufo_v1_ufo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ufo_v1_ufo_proto_rawDesc), len(file_ufo_v1_ufo_proto_rawDesc)))
	})
	return file_ufo_v1_ufo_proto_rawDescData
}

var file_ufo_v1_ufo_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ufo_v1_ufo_proto_goTypes = []any{
	(*SightingInfo)(nil),          // 0: ufo.v1.SightingInfo
	(*Sighting)(nil),              // 1: ufo.v1.Sighting
	(*GetRequest)(nil),            // 2: ufo.v1.GetRequest
	(*GetResponse)(nil),           // 3: ufo.v1.GetResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_ufo_v1_ufo_proto_depIdxs = []int32{
	0, // 0: ufo.v1.Sighting.info:type_name -> ufo.v1.SightingInfo
	4, // 1: ufo.v1.Sighting.created_at:type_name -> google.protobuf.Timestamp
	4, // 2: ufo.v1.Sighting.updated_at:type_name -> google.protobuf.Timestamp
	1, // 3: ufo.v1.GetResponse.sighting:type_name -> ufo.v1.Sighting
	2, // 4: ufo.v1.UFOService.Get:input_type -> ufo.v1.GetRequest
	3, // 5: ufo.v1.UFOService.Get:output_type -> ufo.v1.GetResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ufo_v1_ufo_proto_init() }
func file_ufo_v1_ufo_proto_init() {
	if File_ufo_v1_ufo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ufo_v1_ufo_proto_rawDesc), len(file_ufo_v1_ufo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ufo_v1_ufo_proto_goTypes,
		DependencyIndexes: file_ufo_v1_ufo_proto_depIdxs,
		MessageInfos:      file_ufo_v1_ufo_proto_msgTypes,
	}.Build()
	File_ufo_v1_ufo_proto = out.File
	file_ufo_v1_ufo_proto_goTypes = nil
	file_ufo_v1_ufo_proto_depIdxs = nil
}
