// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: ufo/v1/ufo.proto

package ufo_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UFOService_CreateUfo_FullMethodName = "/ufo.v1.UFOService/CreateUfo"
	UFOService_GetUfo_FullMethodName    = "/ufo.v1.UFOService/GetUfo"
)

// UFOServiceClient is the client API for UFOService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// UFOService — сервис управления наблюдениями НЛО.
type UFOServiceClient interface {
	// CreateUfo создаёт новое наблюдение НЛО.
	CreateUfo(ctx context.Context, in *CreateUfoRequest, opts ...grpc.CallOption) (*CreateUfoResponse, error)
	// GetUfo возвращает наблюдение НЛО по ID.
	GetUfo(ctx context.Context, in *GetUfoRequest, opts ...grpc.CallOption) (*GetUfoResponse, error)
}

type uFOServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUFOServiceClient(cc grpc.ClientConnInterface) UFOServiceClient {
	return &uFOServiceClient{cc}
}

func (c *uFOServiceClient) CreateUfo(ctx context.Context, in *CreateUfoRequest, opts ...grpc.CallOption) (*CreateUfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUfoResponse)
	err := c.cc.Invoke(ctx, UFOService_CreateUfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uFOServiceClient) GetUfo(ctx context.Context, in *GetUfoRequest, opts ...grpc.CallOption) (*GetUfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUfoResponse)
	err := c.cc.Invoke(ctx, UFOService_GetUfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UFOServiceServer is the server API for UFOService service.
// All implementations must embed UnimplementedUFOServiceServer
// for forward compatibility.
//
// UFOService — сервис управления наблюдениями НЛО.
type UFOServiceServer interface {
	// CreateUfo создаёт новое наблюдение НЛО.
	CreateUfo(context.Context, *CreateUfoRequest) (*CreateUfoResponse, error)
	// GetUfo возвращает наблюдение НЛО по ID.
	GetUfo(context.Context, *GetUfoRequest) (*GetUfoResponse, error)
	mustEmbedUnimplementedUFOServiceServer()
}

// UnimplementedUFOServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUFOServiceServer struct{}

func (UnimplementedUFOServiceServer) CreateUfo(context.Context, *CreateUfoRequest) (*CreateUfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUfo not implemented")
}
func (UnimplementedUFOServiceServer) GetUfo(context.Context, *GetUfoRequest) (*GetUfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUfo not implemented")
}
func (UnimplementedUFOServiceServer) mustEmbedUnimplementedUFOServiceServer() {}
func (UnimplementedUFOServiceServer) testEmbeddedByValue()                    {}

// UnsafeUFOServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UFOServiceServer will
// result in compilation errors.
type UnsafeUFOServiceServer interface {
	mustEmbedUnimplementedUFOServiceServer()
}

func RegisterUFOServiceServer(s grpc.ServiceRegistrar, srv UFOServiceServer) {
	// If the following call panics, it indicates UnimplementedUFOServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UFOService_ServiceDesc, srv)
}

func _UFOService_CreateUfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UFOServiceServer).CreateUfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UFOService_CreateUfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UFOServiceServer).CreateUfo(ctx, req.(*CreateUfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UFOService_GetUfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UFOServiceServer).GetUfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UFOService_GetUfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UFOServiceServer).GetUfo(ctx, req.(*GetUfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UFOService_ServiceDesc is the grpc.ServiceDesc for UFOService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UFOService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ufo.v1.UFOService",
	HandlerType: (*UFOServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUfo",
			Handler:    _UFOService_CreateUfo_Handler,
		},
		{
			MethodName: "GetUfo",
			Handler:    _UFOService_GetUfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ufo/v1/ufo.proto",
}
