// Code generated for mbakhodurov service
// © mbakhodurov 2026.

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewWeatherCenterClient creates a new instance of WeatherCenterClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWeatherCenterClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *WeatherCenterClient {
	mock := &WeatherCenterClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WeatherCenterClient is an autogenerated mock type for the WeatherCenterClient type
type WeatherCenterClient struct {
	mock.Mock
}

type WeatherCenterClient_Expecter struct {
	mock *mock.Mock
}

func (_m *WeatherCenterClient) EXPECT() *WeatherCenterClient_Expecter {
	return &WeatherCenterClient_Expecter{mock: &_m.Mock}
}

// GetTemperature provides a mock function for the type WeatherCenterClient
func (_mock *WeatherCenterClient) GetTemperature(city string) (float32, error) {
	ret := _mock.Called(city)

	if len(ret) == 0 {
		panic("no return value specified for GetTemperature")
	}

	var r0 float32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (float32, error)); ok {
		return returnFunc(city)
	}
	if returnFunc, ok := ret.Get(0).(func(string) float32); ok {
		r0 = returnFunc(city)
	} else {
		r0 = ret.Get(0).(float32)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(city)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WeatherCenterClient_GetTemperature_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTemperature'
type WeatherCenterClient_GetTemperature_Call struct {
	*mock.Call
}

// GetTemperature is a helper method to define mock.On call
//   - city string
func (_e *WeatherCenterClient_Expecter) GetTemperature(city interface{}) *WeatherCenterClient_GetTemperature_Call {
	return &WeatherCenterClient_GetTemperature_Call{Call: _e.mock.On("GetTemperature", city)}
}

func (_c *WeatherCenterClient_GetTemperature_Call) Run(run func(city string)) *WeatherCenterClient_GetTemperature_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *WeatherCenterClient_GetTemperature_Call) Return(f float32, err error) *WeatherCenterClient_GetTemperature_Call {
	_c.Call.Return(f, err)
	return _c
}

func (_c *WeatherCenterClient_GetTemperature_Call) RunAndReturn(run func(city string) (float32, error)) *WeatherCenterClient_GetTemperature_Call {
	_c.Call.Return(run)
	return _c
}

// SetTemperature provides a mock function for the type WeatherCenterClient
func (_mock *WeatherCenterClient) SetTemperature(city string, temperature float32) {
	_mock.Called(city, temperature)
	return
}

// WeatherCenterClient_SetTemperature_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTemperature'
type WeatherCenterClient_SetTemperature_Call struct {
	*mock.Call
}

// SetTemperature is a helper method to define mock.On call
//   - city string
//   - temperature float32
func (_e *WeatherCenterClient_Expecter) SetTemperature(city interface{}, temperature interface{}) *WeatherCenterClient_SetTemperature_Call {
	return &WeatherCenterClient_SetTemperature_Call{Call: _e.mock.On("SetTemperature", city, temperature)}
}

func (_c *WeatherCenterClient_SetTemperature_Call) Run(run func(city string, temperature float32)) *WeatherCenterClient_SetTemperature_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 float32
		if args[1] != nil {
			arg1 = args[1].(float32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *WeatherCenterClient_SetTemperature_Call) Return() *WeatherCenterClient_SetTemperature_Call {
	_c.Call.Return()
	return _c
}

func (_c *WeatherCenterClient_SetTemperature_Call) RunAndReturn(run func(city string, temperature float32)) *WeatherCenterClient_SetTemperature_Call {
	_c.Run(run)
	return _c
}
