// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ufo/v1/ufo.proto

package ufo_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateUfoRequest — запрос на создание наблюдения НЛО.
type CreateUfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Заголовок наблюдения.
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// Описание наблюдения.
	Content       string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUfoRequest) Reset() {
	*x = CreateUfoRequest{}
	mi := &file_ufo_v1_ufo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUfoRequest) ProtoMessage() {}

func (x *CreateUfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ufo_v1_ufo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUfoRequest.ProtoReflect.Descriptor instead.
func (*CreateUfoRequest) Descriptor() ([]byte, []int) {
	return file_ufo_v1_ufo_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUfoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateUfoRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// CreateUfoResponse — ответ с ID созданного наблюдения НЛО.
type CreateUfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Идентификатор созданного наблюдения.
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUfoResponse) Reset() {
	*x = CreateUfoResponse{}
	mi := &file_ufo_v1_ufo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUfoResponse) ProtoMessage() {}

func (x *CreateUfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ufo_v1_ufo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUfoResponse.ProtoReflect.Descriptor instead.
func (*CreateUfoResponse) Descriptor() ([]byte, []int) {
	return file_ufo_v1_ufo_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUfoResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// GetUfoRequest — запрос на получение наблюдения НЛО.
type GetUfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Идентификатор наблюдения.
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUfoRequest) Reset() {
	*x = GetUfoRequest{}
	mi := &file_ufo_v1_ufo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUfoRequest) ProtoMessage() {}

func (x *GetUfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ufo_v1_ufo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUfoRequest.ProtoReflect.Descriptor instead.
func (*GetUfoRequest) Descriptor() ([]byte, []int) {
	return file_ufo_v1_ufo_proto_rawDescGZIP(), []int{2}
}

func (x *GetUfoRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// GetUfoResponse — ответ с данными наблюдения НЛО.
type GetUfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Идентификатор наблюдения.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Заголовок наблюдения.
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Описание наблюдения.
	Content       string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUfoResponse) Reset() {
	*x = GetUfoResponse{}
	mi := &file_ufo_v1_ufo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUfoResponse) ProtoMessage() {}

func (x *GetUfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ufo_v1_ufo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUfoResponse.ProtoReflect.Descriptor instead.
func (*GetUfoResponse) Descriptor() ([]byte, []int) {
	return file_ufo_v1_ufo_proto_rawDescGZIP(), []int{3}
}

func (x *GetUfoResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetUfoResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetUfoResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// SetFailModeRequest — запрос на включение/выключение режима сбоев.
type SetFailModeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Флаг включения режима сбоев.
	Enabled       bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFailModeRequest) Reset() {
	*x = SetFailModeRequest{}
	mi := &file_ufo_v1_ufo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFailModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFailModeRequest) ProtoMessage() {}

func (x *SetFailModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ufo_v1_ufo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFailModeRequest.ProtoReflect.Descriptor instead.
func (*SetFailModeRequest) Descriptor() ([]byte, []int) {
	return file_ufo_v1_ufo_proto_rawDescGZIP(), []int{4}
}

func (x *SetFailModeRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

// SetFailModeResponse — ответ на запрос изменения режима сбоев.
type SetFailModeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFailModeResponse) Reset() {
	*x = SetFailModeResponse{}
	mi := &file_ufo_v1_ufo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFailModeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFailModeResponse) ProtoMessage() {}

func (x *SetFailModeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ufo_v1_ufo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFailModeResponse.ProtoReflect.Descriptor instead.
func (*SetFailModeResponse) Descriptor() ([]byte, []int) {
	return file_ufo_v1_ufo_proto_rawDescGZIP(), []int{5}
}

var File_ufo_v1_ufo_proto protoreflect.FileDescriptor

const file_ufo_v1_ufo_proto_rawDesc = "" +
	"\n" +
	"\x10ufo/v1/ufo.proto\x12\x06ufo.v1\"B\n" +
	"\x10CreateUfoRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"#\n" +
	"\x11CreateUfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x1f\n" +
	"\rGetUfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"P\n" +
	"\x0eGetUfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\".\n" +
	"\x12SetFailModeRequest\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\"\x15\n" +
	"\x13SetFailModeResponse2\xcf\x01\n" +
	"\n" +
	"UFOService\x12@\n" +
	"\tCreateUfo\x12\x18.ufo.v1.CreateUfoRequest\x1a\x19.ufo.v1.CreateUfoResponse\x127\n" +
	"\x06GetUfo\x12\x15.ufo.v1.GetUfoRequest\x1a\x16.ufo.v1.GetUfoResponse\x12F\n" +
	"\vSetFailMode\x12\x1a.ufo.v1.SetFailModeRequest\x1a\x1b.ufo.v1.SetFailModeResponseBVZTgithub.com/mbakhodurov/examples2/week_8/easy_circuit_breaker/pkg/proto/ufo/v1;ufo_v1b\x06proto3"

var (
	file_ufo_v1_ufo_proto_rawDescOnce sync.Once
	file_ufo_v1_ufo_proto_rawDescData []byte
)

func file_ufo_v1_ufo_proto_rawDescGZIP() []byte {
	file_ufo_v1_ufo_proto_rawDescOnce.Do(func() {
		file_ufo_v1_ufo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ufo_v1_ufo_proto_rawDesc), len(file_ufo_v1_ufo_proto_rawDesc)))
	})
	return file_ufo_v1_ufo_proto_rawDescData
}

var file_ufo_v1_ufo_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_ufo_v1_ufo_proto_goTypes = []any{
	(*CreateUfoRequest)(nil),    // 0: ufo.v1.CreateUfoRequest
	(*CreateUfoResponse)(nil),   // 1: ufo.v1.CreateUfoResponse
	(*GetUfoRequest)(nil),       // 2: ufo.v1.GetUfoRequest
	(*GetUfoResponse)(nil),      // 3: ufo.v1.GetUfoResponse
	(*SetFailModeRequest)(nil),  // 4: ufo.v1.SetFailModeRequest
	(*SetFailModeResponse)(nil), // 5: ufo.v1.SetFailModeResponse
}
var file_ufo_v1_ufo_proto_depIdxs = []int32{
	0, // 0: ufo.v1.UFOService.CreateUfo:input_type -> ufo.v1.CreateUfoRequest
	2, // 1: ufo.v1.UFOService.GetUfo:input_type -> ufo.v1.GetUfoRequest
	4, // 2: ufo.v1.UFOService.SetFailMode:input_type -> ufo.v1.SetFailModeRequest
	1, // 3: ufo.v1.UFOService.CreateUfo:output_type -> ufo.v1.CreateUfoResponse
	3, // 4: ufo.v1.UFOService.GetUfo:output_type -> ufo.v1.GetUfoResponse
	5, // 5: ufo.v1.UFOService.SetFailMode:output_type -> ufo.v1.SetFailModeResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ufo_v1_ufo_proto_init() }
func file_ufo_v1_ufo_proto_init() {
	if File_ufo_v1_ufo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ufo_v1_ufo_proto_rawDesc), len(file_ufo_v1_ufo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ufo_v1_ufo_proto_goTypes,
		DependencyIndexes: file_ufo_v1_ufo_proto_depIdxs,
		MessageInfos:      file_ufo_v1_ufo_proto_msgTypes,
	}.Build()
	File_ufo_v1_ufo_proto = out.File
	file_ufo_v1_ufo_proto_goTypes = nil
	file_ufo_v1_ufo_proto_depIdxs = nil
}
