// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ufo/v1/ufo.proto

// Package ufo.v1 содержит API для работы с наблюдениями НЛО

package ufo_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Sighting представляет полную информацию о наблюдении НЛО
type Sighting struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uuid уникальный идентификатор наблюдения
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// observed_at время наблюдения НЛО
	ObservedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	// location место наблюдения
	Location string `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	// description описание наблюдаемого объекта
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// color цвет объекта (опционально)
	Color *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`
	// sound признак наличия звука (опционально)
	Sound *wrapperspb.BoolValue `protobuf:"bytes,6,opt,name=sound,proto3" json:"sound,omitempty"`
	// duration_seconds продолжительность наблюдения в секундах (опционально)
	DurationSeconds *wrapperspb.Int32Value `protobuf:"bytes,7,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	// created_at время создания записи
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// updated_at время последнего обновления записи
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// deleted_at время удаления записи (опционально)
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sighting) Reset() {
	*x = Sighting{}
	mi := &file_ufo_v1_ufo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sighting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sighting) ProtoMessage() {}

func (x *Sighting) ProtoReflect() protoreflect.Message {
	mi := &file_ufo_v1_ufo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sighting.ProtoReflect.Descriptor instead.
func (*Sighting) Descriptor() ([]byte, []int) {
	return file_ufo_v1_ufo_proto_rawDescGZIP(), []int{0}
}

func (x *Sighting) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Sighting) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *Sighting) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Sighting) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Sighting) GetColor() *wrapperspb.StringValue {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *Sighting) GetSound() *wrapperspb.BoolValue {
	if x != nil {
		return x.Sound
	}
	return nil
}

func (x *Sighting) GetDurationSeconds() *wrapperspb.Int32Value {
	if x != nil {
		return x.DurationSeconds
	}
	return nil
}

func (x *Sighting) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Sighting) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Sighting) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

// CreateRequest запрос на создание наблюдения НЛО
type CreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// observed_at время наблюдения НЛО
	ObservedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	// location место наблюдения
	Location string `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	// description описание наблюдаемого объекта
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// color цвет объекта (опционально)
	Color *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	// sound признак наличия звука (опционально)
	Sound *wrapperspb.BoolValue `protobuf:"bytes,5,opt,name=sound,proto3" json:"sound,omitempty"`
	// duration_seconds продолжительность наблюдения в секундах (опционально)
	DurationSeconds *wrapperspb.Int32Value `protobuf:"bytes,6,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_ufo_v1_ufo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ufo_v1_ufo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_ufo_v1_ufo_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRequest) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *CreateRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateRequest) GetColor() *wrapperspb.StringValue {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *CreateRequest) GetSound() *wrapperspb.BoolValue {
	if x != nil {
		return x.Sound
	}
	return nil
}

func (x *CreateRequest) GetDurationSeconds() *wrapperspb.Int32Value {
	if x != nil {
		return x.DurationSeconds
	}
	return nil
}

// CreateResponse ответ на запрос создания наблюдения
type CreateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uuid идентификатор созданного наблюдения
	Uuid          string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_ufo_v1_ufo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ufo_v1_ufo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_ufo_v1_ufo_proto_rawDescGZIP(), []int{2}
}

func (x *CreateResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// GetRequest запрос на получение наблюдения по идентификатору
type GetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uuid идентификатор наблюдения
	Uuid          string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_ufo_v1_ufo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ufo_v1_ufo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_ufo_v1_ufo_proto_rawDescGZIP(), []int{3}
}

func (x *GetRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// GetResponse ответ с данными наблюдения
type GetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sighting данные наблюдения
	Sighting      *Sighting `protobuf:"bytes,1,opt,name=sighting,proto3" json:"sighting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_ufo_v1_ufo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ufo_v1_ufo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_ufo_v1_ufo_proto_rawDescGZIP(), []int{4}
}

func (x *GetResponse) GetSighting() *Sighting {
	if x != nil {
		return x.Sighting
	}
	return nil
}

// UpdateRequest запрос на обновление наблюдения
type UpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uuid идентификатор наблюдения для обновления
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// observed_at время наблюдения НЛО (опционально)
	ObservedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	// location место наблюдения (опционально)
	Location *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	// description описание наблюдаемого объекта (опционально)
	Description *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// color цвет объекта (опционально)
	Color *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`
	// sound признак наличия звука (опционально)
	Sound *wrapperspb.BoolValue `protobuf:"bytes,6,opt,name=sound,proto3" json:"sound,omitempty"`
	// duration_seconds продолжительность наблюдения в секундах (опционально)
	DurationSeconds *wrapperspb.Int32Value `protobuf:"bytes,7,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_ufo_v1_ufo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ufo_v1_ufo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_ufo_v1_ufo_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UpdateRequest) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *UpdateRequest) GetLocation() *wrapperspb.StringValue {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *UpdateRequest) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *UpdateRequest) GetColor() *wrapperspb.StringValue {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *UpdateRequest) GetSound() *wrapperspb.BoolValue {
	if x != nil {
		return x.Sound
	}
	return nil
}

func (x *UpdateRequest) GetDurationSeconds() *wrapperspb.Int32Value {
	if x != nil {
		return x.DurationSeconds
	}
	return nil
}

// DeleteRequest запрос на удаление наблюдения
type DeleteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uuid идентификатор наблюдения для удаления
	Uuid          string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_ufo_v1_ufo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ufo_v1_ufo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_ufo_v1_ufo_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// UpdateResponse ответ на обновление наблюдения
type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_ufo_v1_ufo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ufo_v1_ufo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_ufo_v1_ufo_proto_rawDescGZIP(), []int{7}
}

// DeleteResponse ответ на удаление наблюдения
type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_ufo_v1_ufo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ufo_v1_ufo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_ufo_v1_ufo_proto_rawDescGZIP(), []int{8}
}

var File_ufo_v1_ufo_proto protoreflect.FileDescriptor

const file_ufo_v1_ufo_proto_rawDesc = "" +
	"\n" +
	"\x10ufo/v1/ufo.proto\x12\x06ufo.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xf8\x03\n" +
	"\bSighting\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12;\n" +
	"\vobserved_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x122\n" +
	"\x05color\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\x05color\x120\n" +
	"\x05sound\x18\x06 \x01(\v2\x1a.google.protobuf.BoolValueR\x05sound\x12F\n" +
	"\x10duration_seconds\x18\a \x01(\v2\x1b.google.protobuf.Int32ValueR\x0fdurationSeconds\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"\xb8\x02\n" +
	"\rCreateRequest\x12;\n" +
	"\vobserved_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x122\n" +
	"\x05color\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\x05color\x120\n" +
	"\x05sound\x18\x05 \x01(\v2\x1a.google.protobuf.BoolValueR\x05sound\x12F\n" +
	"\x10duration_seconds\x18\x06 \x01(\v2\x1b.google.protobuf.Int32ValueR\x0fdurationSeconds\"$\n" +
	"\x0eCreateResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\" \n" +
	"\n" +
	"GetRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\";\n" +
	"\vGetResponse\x12,\n" +
	"\bsighting\x18\x01 \x01(\v2\x10.ufo.v1.SightingR\bsighting\"\x88\x03\n" +
	"\rUpdateRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12;\n" +
	"\vobserved_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x128\n" +
	"\blocation\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\blocation\x12>\n" +
	"\vdescription\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\x122\n" +
	"\x05color\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\x05color\x120\n" +
	"\x05sound\x18\x06 \x01(\v2\x1a.google.protobuf.BoolValueR\x05sound\x12F\n" +
	"\x10duration_seconds\x18\a \x01(\v2\x1b.google.protobuf.Int32ValueR\x0fdurationSeconds\"#\n" +
	"\rDeleteRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\x10\n" +
	"\x0eUpdateResponse\"\x10\n" +
	"\x0eDeleteResponse2\xe7\x01\n" +
	"\n" +
	"UFOService\x127\n" +
	"\x06Create\x12\x15.ufo.v1.CreateRequest\x1a\x16.ufo.v1.CreateResponse\x12.\n" +
	"\x03Get\x12\x12.ufo.v1.GetRequest\x1a\x13.ufo.v1.GetResponse\x127\n" +
	"\x06Update\x12\x15.ufo.v1.UpdateRequest\x1a\x16.ufo.v1.UpdateResponse\x127\n" +
	"\x06Delete\x12\x15.ufo.v1.DeleteRequest\x1a\x16.ufo.v1.DeleteResponseBRZPgithub.com/mbakhodurov/examples2/week_3/workspace/shared/pkg/proto/ufo/v1;ufo_v1b\x06proto3"

var (
	file_ufo_v1_ufo_proto_rawDescOnce sync.Once
	file_ufo_v1_ufo_proto_rawDescData []byte
)

func file_ufo_v1_ufo_proto_rawDescGZIP() []byte {
	file_ufo_v1_ufo_proto_rawDescOnce.Do(func() {
		file_ufo_v1_ufo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ufo_v1_ufo_proto_rawDesc), len(file_ufo_v1_ufo_proto_rawDesc)))
	})
	return file_ufo_v1_ufo_proto_rawDescData
}

var file_ufo_v1_ufo_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_ufo_v1_ufo_proto_goTypes = []any{
	(*Sighting)(nil),               // 0: ufo.v1.Sighting
	(*CreateRequest)(nil),          // 1: ufo.v1.CreateRequest
	(*CreateResponse)(nil),         // 2: ufo.v1.CreateResponse
	(*GetRequest)(nil),             // 3: ufo.v1.GetRequest
	(*GetResponse)(nil),            // 4: ufo.v1.GetResponse
	(*UpdateRequest)(nil),          // 5: ufo.v1.UpdateRequest
	(*DeleteRequest)(nil),          // 6: ufo.v1.DeleteRequest
	(*UpdateResponse)(nil),         // 7: ufo.v1.UpdateResponse
	(*DeleteResponse)(nil),         // 8: ufo.v1.DeleteResponse
	(*timestamppb.Timestamp)(nil),  // 9: google.protobuf.Timestamp
	(*wrapperspb.StringValue)(nil), // 10: google.protobuf.StringValue
	(*wrapperspb.BoolValue)(nil),   // 11: google.protobuf.BoolValue
	(*wrapperspb.Int32Value)(nil),  // 12: google.protobuf.Int32Value
}
var file_ufo_v1_ufo_proto_depIdxs = []int32{
	9,  // 0: ufo.v1.Sighting.observed_at:type_name -> google.protobuf.Timestamp
	10, // 1: ufo.v1.Sighting.color:type_name -> google.protobuf.StringValue
	11, // 2: ufo.v1.Sighting.sound:type_name -> google.protobuf.BoolValue
	12, // 3: ufo.v1.Sighting.duration_seconds:type_name -> google.protobuf.Int32Value
	9,  // 4: ufo.v1.Sighting.created_at:type_name -> google.protobuf.Timestamp
	9,  // 5: ufo.v1.Sighting.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 6: ufo.v1.Sighting.deleted_at:type_name -> google.protobuf.Timestamp
	9,  // 7: ufo.v1.CreateRequest.observed_at:type_name -> google.protobuf.Timestamp
	10, // 8: ufo.v1.CreateRequest.color:type_name -> google.protobuf.StringValue
	11, // 9: ufo.v1.CreateRequest.sound:type_name -> google.protobuf.BoolValue
	12, // 10: ufo.v1.CreateRequest.duration_seconds:type_name -> google.protobuf.Int32Value
	0,  // 11: ufo.v1.GetResponse.sighting:type_name -> ufo.v1.Sighting
	9,  // 12: ufo.v1.UpdateRequest.observed_at:type_name -> google.protobuf.Timestamp
	10, // 13: ufo.v1.UpdateRequest.location:type_name -> google.protobuf.StringValue
	10, // 14: ufo.v1.UpdateRequest.description:type_name -> google.protobuf.StringValue
	10, // 15: ufo.v1.UpdateRequest.color:type_name -> google.protobuf.StringValue
	11, // 16: ufo.v1.UpdateRequest.sound:type_name -> google.protobuf.BoolValue
	12, // 17: ufo.v1.UpdateRequest.duration_seconds:type_name -> google.protobuf.Int32Value
	1,  // 18: ufo.v1.UFOService.Create:input_type -> ufo.v1.CreateRequest
	3,  // 19: ufo.v1.UFOService.Get:input_type -> ufo.v1.GetRequest
	5,  // 20: ufo.v1.UFOService.Update:input_type -> ufo.v1.UpdateRequest
	6,  // 21: ufo.v1.UFOService.Delete:input_type -> ufo.v1.DeleteRequest
	2,  // 22: ufo.v1.UFOService.Create:output_type -> ufo.v1.CreateResponse
	4,  // 23: ufo.v1.UFOService.Get:output_type -> ufo.v1.GetResponse
	7,  // 24: ufo.v1.UFOService.Update:output_type -> ufo.v1.UpdateResponse
	8,  // 25: ufo.v1.UFOService.Delete:output_type -> ufo.v1.DeleteResponse
	22, // [22:26] is the sub-list for method output_type
	18, // [18:22] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_ufo_v1_ufo_proto_init() }
func file_ufo_v1_ufo_proto_init() {
	if File_ufo_v1_ufo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ufo_v1_ufo_proto_rawDesc), len(file_ufo_v1_ufo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ufo_v1_ufo_proto_goTypes,
		DependencyIndexes: file_ufo_v1_ufo_proto_depIdxs,
		MessageInfos:      file_ufo_v1_ufo_proto_msgTypes,
	}.Build()
	File_ufo_v1_ufo_proto = out.File
	file_ufo_v1_ufo_proto_goTypes = nil
	file_ufo_v1_ufo_proto_depIdxs = nil
}
