// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: ufo/v1/ufo.proto

package ufo_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UFOService_Get_FullMethodName    = "/ufo.v1.UFOService/Get"
	UFOService_List_FullMethodName   = "/ufo.v1.UFOService/List"
	UFOService_Create_FullMethodName = "/ufo.v1.UFOService/Create"
)

// UFOServiceClient is the client API for UFOService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// UFOService управляет информацией о наблюдениях НЛО
type UFOServiceClient interface {
	// Get возвращает информацию о наблюдении по ID
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	// List возвращает список всех наблюдений
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	// Create создаёт новое наблюдение
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
}

type uFOServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUFOServiceClient(cc grpc.ClientConnInterface) UFOServiceClient {
	return &uFOServiceClient{cc}
}

func (c *uFOServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, UFOService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uFOServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, UFOService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uFOServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, UFOService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UFOServiceServer is the server API for UFOService service.
// All implementations must embed UnimplementedUFOServiceServer
// for forward compatibility.
//
// UFOService управляет информацией о наблюдениях НЛО
type UFOServiceServer interface {
	// Get возвращает информацию о наблюдении по ID
	Get(context.Context, *GetRequest) (*GetResponse, error)
	// List возвращает список всех наблюдений
	List(context.Context, *ListRequest) (*ListResponse, error)
	// Create создаёт новое наблюдение
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	mustEmbedUnimplementedUFOServiceServer()
}

// UnimplementedUFOServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUFOServiceServer struct{}

func (UnimplementedUFOServiceServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedUFOServiceServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedUFOServiceServer) Create(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedUFOServiceServer) mustEmbedUnimplementedUFOServiceServer() {}
func (UnimplementedUFOServiceServer) testEmbeddedByValue()                    {}

// UnsafeUFOServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UFOServiceServer will
// result in compilation errors.
type UnsafeUFOServiceServer interface {
	mustEmbedUnimplementedUFOServiceServer()
}

func RegisterUFOServiceServer(s grpc.ServiceRegistrar, srv UFOServiceServer) {
	// If the following call panics, it indicates UnimplementedUFOServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UFOService_ServiceDesc, srv)
}

func _UFOService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UFOServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UFOService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UFOServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UFOService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UFOServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UFOService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UFOServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UFOService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UFOServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UFOService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UFOServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UFOService_ServiceDesc is the grpc.ServiceDesc for UFOService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UFOService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ufo.v1.UFOService",
	HandlerType: (*UFOServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _UFOService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _UFOService_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _UFOService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ufo/v1/ufo.proto",
}
