// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: weather/v1/weather.proto

// Package weather.v1 содержит API для получения данных о погоде

package weather_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetCurrentWeatherRequest запрос на получение текущей погоды
type GetCurrentWeatherRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// location местоположение (город, координаты и т.д.)
	Location      string `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentWeatherRequest) Reset() {
	*x = GetCurrentWeatherRequest{}
	mi := &file_weather_v1_weather_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentWeatherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentWeatherRequest) ProtoMessage() {}

func (x *GetCurrentWeatherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_weather_v1_weather_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentWeatherRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentWeatherRequest) Descriptor() ([]byte, []int) {
	return file_weather_v1_weather_proto_rawDescGZIP(), []int{0}
}

func (x *GetCurrentWeatherRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

// GetCurrentWeatherResponse ответ с данными о текущей погоде
type GetCurrentWeatherResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// conditions текущие погодные условия
	Conditions    *WeatherConditions `protobuf:"bytes,1,opt,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentWeatherResponse) Reset() {
	*x = GetCurrentWeatherResponse{}
	mi := &file_weather_v1_weather_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentWeatherResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentWeatherResponse) ProtoMessage() {}

func (x *GetCurrentWeatherResponse) ProtoReflect() protoreflect.Message {
	mi := &file_weather_v1_weather_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentWeatherResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentWeatherResponse) Descriptor() ([]byte, []int) {
	return file_weather_v1_weather_proto_rawDescGZIP(), []int{1}
}

func (x *GetCurrentWeatherResponse) GetConditions() *WeatherConditions {
	if x != nil {
		return x.Conditions
	}
	return nil
}

// WeatherConditions описание погодных условий
type WeatherConditions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// description описание погоды (ясно, облачно, дождь и т.д.)
	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// temperature_celsius температура в градусах Цельсия
	TemperatureCelsius float64 `protobuf:"fixed64,2,opt,name=temperature_celsius,json=temperatureCelsius,proto3" json:"temperature_celsius,omitempty"`
	// visibility_km видимость в километрах
	VisibilityKm  float64 `protobuf:"fixed64,3,opt,name=visibility_km,json=visibilityKm,proto3" json:"visibility_km,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeatherConditions) Reset() {
	*x = WeatherConditions{}
	mi := &file_weather_v1_weather_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherConditions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherConditions) ProtoMessage() {}

func (x *WeatherConditions) ProtoReflect() protoreflect.Message {
	mi := &file_weather_v1_weather_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherConditions.ProtoReflect.Descriptor instead.
func (*WeatherConditions) Descriptor() ([]byte, []int) {
	return file_weather_v1_weather_proto_rawDescGZIP(), []int{2}
}

func (x *WeatherConditions) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WeatherConditions) GetTemperatureCelsius() float64 {
	if x != nil {
		return x.TemperatureCelsius
	}
	return 0
}

func (x *WeatherConditions) GetVisibilityKm() float64 {
	if x != nil {
		return x.VisibilityKm
	}
	return 0
}

var File_weather_v1_weather_proto protoreflect.FileDescriptor

const file_weather_v1_weather_proto_rawDesc = "" +
	"\n" +
	"\x18weather/v1/weather.proto\x12\n" +
	"weather.v1\"6\n" +
	"\x18GetCurrentWeatherRequest\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\"Z\n" +
	"\x19GetCurrentWeatherResponse\x12=\n" +
	"\n" +
	"conditions\x18\x01 \x01(\v2\x1d.weather.v1.WeatherConditionsR\n" +
	"conditions\"\x8b\x01\n" +
	"\x11WeatherConditions\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12/\n" +
	"\x13temperature_celsius\x18\x02 \x01(\x01R\x12temperatureCelsius\x12#\n" +
	"\rvisibility_km\x18\x03 \x01(\x01R\fvisibilityKm2r\n" +
	"\x0eWeatherService\x12`\n" +
	"\x11GetCurrentWeather\x12$.weather.v1.GetCurrentWeatherRequest\x1a%.weather.v1.GetCurrentWeatherResponseBPZNgithub.com/mbakhodurov/examples2/week_2/layers/pkg/proto/weather/v1;weather_v1b\x06proto3"

var (
	file_weather_v1_weather_proto_rawDescOnce sync.Once
	file_weather_v1_weather_proto_rawDescData []byte
)

func file_weather_v1_weather_proto_rawDescGZIP() []byte {
	file_weather_v1_weather_proto_rawDescOnce.Do(func() {
		file_weather_v1_weather_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_weather_v1_weather_proto_rawDesc), len(file_weather_v1_weather_proto_rawDesc)))
	})
	return file_weather_v1_weather_proto_rawDescData
}

var file_weather_v1_weather_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_weather_v1_weather_proto_goTypes = []any{
	(*GetCurrentWeatherRequest)(nil),  // 0: weather.v1.GetCurrentWeatherRequest
	(*GetCurrentWeatherResponse)(nil), // 1: weather.v1.GetCurrentWeatherResponse
	(*WeatherConditions)(nil),         // 2: weather.v1.WeatherConditions
}
var file_weather_v1_weather_proto_depIdxs = []int32{
	2, // 0: weather.v1.GetCurrentWeatherResponse.conditions:type_name -> weather.v1.WeatherConditions
	0, // 1: weather.v1.WeatherService.GetCurrentWeather:input_type -> weather.v1.GetCurrentWeatherRequest
	1, // 2: weather.v1.WeatherService.GetCurrentWeather:output_type -> weather.v1.GetCurrentWeatherResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_weather_v1_weather_proto_init() }
func file_weather_v1_weather_proto_init() {
	if File_weather_v1_weather_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_weather_v1_weather_proto_rawDesc), len(file_weather_v1_weather_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_weather_v1_weather_proto_goTypes,
		DependencyIndexes: file_weather_v1_weather_proto_depIdxs,
		MessageInfos:      file_weather_v1_weather_proto_msgTypes,
	}.Build()
	File_weather_v1_weather_proto = out.File
	file_weather_v1_weather_proto_goTypes = nil
	file_weather_v1_weather_proto_depIdxs = nil
}
