// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: analysis/v1/analysis.proto

package analysis_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AnalyzeSightingRequest запрос на анализ наблюдения НЛО
type AnalyzeSightingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uuid идентификатор наблюдения для анализа
	Uuid          string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeSightingRequest) Reset() {
	*x = AnalyzeSightingRequest{}
	mi := &file_analysis_v1_analysis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeSightingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeSightingRequest) ProtoMessage() {}

func (x *AnalyzeSightingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_v1_analysis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeSightingRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeSightingRequest) Descriptor() ([]byte, []int) {
	return file_analysis_v1_analysis_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeSightingRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// AnalyzeSightingResponse результат анализа наблюдения
type AnalyzeSightingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// analysis_result текстовый результат анализа
	AnalysisResult string `protobuf:"bytes,1,opt,name=analysis_result,json=analysisResult,proto3" json:"analysis_result,omitempty"`
	// classification классификация наблюдаемого объекта
	Classification string `protobuf:"bytes,2,opt,name=classification,proto3" json:"classification,omitempty"`
	// confidence_score уровень уверенности в результате
	ConfidenceScore float32 `protobuf:"fixed32,3,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AnalyzeSightingResponse) Reset() {
	*x = AnalyzeSightingResponse{}
	mi := &file_analysis_v1_analysis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeSightingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeSightingResponse) ProtoMessage() {}

func (x *AnalyzeSightingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_v1_analysis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeSightingResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeSightingResponse) Descriptor() ([]byte, []int) {
	return file_analysis_v1_analysis_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeSightingResponse) GetAnalysisResult() string {
	if x != nil {
		return x.AnalysisResult
	}
	return ""
}

func (x *AnalyzeSightingResponse) GetClassification() string {
	if x != nil {
		return x.Classification
	}
	return ""
}

func (x *AnalyzeSightingResponse) GetConfidenceScore() float32 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

var File_analysis_v1_analysis_proto protoreflect.FileDescriptor

const file_analysis_v1_analysis_proto_rawDesc = "" +
	"\n" +
	"\x1aanalysis/v1/analysis.proto\x12\vanalysis.v1\",\n" +
	"\x16AnalyzeSightingRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\x95\x01\n" +
	"\x17AnalyzeSightingResponse\x12'\n" +
	"\x0fanalysis_result\x18\x01 \x01(\tR\x0eanalysisResult\x12&\n" +
	"\x0eclassification\x18\x02 \x01(\tR\x0eclassification\x12)\n" +
	"\x10confidence_score\x18\x03 \x01(\x02R\x0fconfidenceScore2o\n" +
	"\x0fAnalysisService\x12\\\n" +
	"\x0fAnalyzeSighting\x12#.analysis.v1.AnalyzeSightingRequest\x1a$.analysis.v1.AnalyzeSightingResponseBZZXgithub.com/mbakhodurov/homeworks2/week7/tracing/shared/pkg/proto/analysis/v1;analysis_v1b\x06proto3"

var (
	file_analysis_v1_analysis_proto_rawDescOnce sync.Once
	file_analysis_v1_analysis_proto_rawDescData []byte
)

func file_analysis_v1_analysis_proto_rawDescGZIP() []byte {
	file_analysis_v1_analysis_proto_rawDescOnce.Do(func() {
		file_analysis_v1_analysis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analysis_v1_analysis_proto_rawDesc), len(file_analysis_v1_analysis_proto_rawDesc)))
	})
	return file_analysis_v1_analysis_proto_rawDescData
}

var file_analysis_v1_analysis_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_analysis_v1_analysis_proto_goTypes = []any{
	(*AnalyzeSightingRequest)(nil),  // 0: analysis.v1.AnalyzeSightingRequest
	(*AnalyzeSightingResponse)(nil), // 1: analysis.v1.AnalyzeSightingResponse
}
var file_analysis_v1_analysis_proto_depIdxs = []int32{
	0, // 0: analysis.v1.AnalysisService.AnalyzeSighting:input_type -> analysis.v1.AnalyzeSightingRequest
	1, // 1: analysis.v1.AnalysisService.AnalyzeSighting:output_type -> analysis.v1.AnalyzeSightingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_analysis_v1_analysis_proto_init() }
func file_analysis_v1_analysis_proto_init() {
	if File_analysis_v1_analysis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analysis_v1_analysis_proto_rawDesc), len(file_analysis_v1_analysis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analysis_v1_analysis_proto_goTypes,
		DependencyIndexes: file_analysis_v1_analysis_proto_depIdxs,
		MessageInfos:      file_analysis_v1_analysis_proto_msgTypes,
	}.Build()
	File_analysis_v1_analysis_proto = out.File
	file_analysis_v1_analysis_proto_goTypes = nil
	file_analysis_v1_analysis_proto_depIdxs = nil
}
