version: '3'

vars:
  GO_VERSION: '1.26.0'
  GOLANGCI_LINT_VERSION: 'v2.12.2'
  GCI_VERSION: 'v0.14.0'
  GOFUMPT_VERSION: 'v0.10.0'
  MOCKERY_VERSION: 'v3.7.0'

  BIN_DIR: '{{.ROOT_DIR}}/bin'
  GOLANGCI_LINT: '{{.BIN_DIR}}/golangci-lint'
  GCI: '{{.BIN_DIR}}/gci'
  GOFUMPT: '{{.BIN_DIR}}/gofumpt'
  MOCKERY: '{{.BIN_DIR}}/mockery'

tasks:
  formatters:install:
    desc: "Устанавливает gofumpt и gci"
    cmds:
      - echo '📦 Устанавливаем gofumpt...'
      - GOBIN={{.BIN_DIR}} go install mvdan.cc/gofumpt@{{.GOFUMPT_VERSION}}
      - echo '📦 Устанавливаем gci...'
      - GOBIN={{.BIN_DIR}} go install github.com/daixiang0/gci@{{.GCI_VERSION}}
    status:
      - test -x {{.GOFUMPT}}
      - test -x {{.GCI}}

  golangci-lint:install:
    desc: "Устанавливает golangci-lint"
    cmds:
      - echo '📦 Устанавливаем golangci-lint...'
      - GOBIN={{.BIN_DIR}} go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{.GOLANGCI_LINT_VERSION}}
    status:
      - test -x {{.GOLANGCI_LINT}}

  mockery:install:
    desc: "Устанавливает mockery"
    cmds:
      - echo '📦 Устанавливаем mockery...'
      - GOBIN={{.BIN_DIR}} go install github.com/vektra/mockery/v3@{{.MOCKERY_VERSION}}
    status:
      - test -x {{.MOCKERY}}

  setup:
    desc: "Устанавливает все инструменты"
    deps: [formatters:install, golangci-lint:install, mockery:install]

  format:
    desc: "Форматирует код (gofumpt + gci)"
    deps: [formatters:install]
    cmds:
      - echo '🧹 Форматируем код через gofumpt...'
      - find . -type f -name '*.go' ! -path '*/mocks/*' ! -path '*/pkg/proto/*' -exec {{.GOFUMPT}} -extra -w {} +
      - echo '📦 Сортируем импорты через gci...'
      - find . -type f -name '*.go' ! -path '*/mocks/*' ! -path '*/pkg/proto/*' -exec {{.GCI}} write -s standard -s default -s "prefix(github.com/olezhek28-courses/microservices-course-examples/)" {} +

  lint:
    desc: "Запускает golangci-lint"
    deps: [golangci-lint:install]
    cmds:
      - '{{.GOLANGCI_LINT}} run --allow-parallel-runners ./... --config=.golangci.yml'

  mocks:gen:
    desc: "Генерирует моки интерфейсов"
    deps: [mockery:install]
    cmds:
      - echo '🧪 Генерация моков...'
      - '{{.MOCKERY}}'

  test:
    desc: "Запускает unit-тесты"
    cmds:
      - go test -v ./...
