// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: classification/v1/classification.proto

package classification_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClassifyObjectRequest запрос на классификацию объекта
type ClassifyObjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// description описание наблюдаемого объекта
	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// color цвет объекта
	Color string `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	// duration_seconds продолжительность наблюдения в секундах
	DurationSeconds int32 `protobuf:"varint,3,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClassifyObjectRequest) Reset() {
	*x = ClassifyObjectRequest{}
	mi := &file_classification_v1_classification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyObjectRequest) ProtoMessage() {}

func (x *ClassifyObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_classification_v1_classification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyObjectRequest.ProtoReflect.Descriptor instead.
func (*ClassifyObjectRequest) Descriptor() ([]byte, []int) {
	return file_classification_v1_classification_proto_rawDescGZIP(), []int{0}
}

func (x *ClassifyObjectRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ClassifyObjectRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *ClassifyObjectRequest) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

// ClassifyObjectResponse результат классификации объекта
type ClassifyObjectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object_type тип классифицированного объекта
	ObjectType string `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	// confidence уровень уверенности в классификации
	Confidence float32 `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	// explanation пояснение к результату классификации
	Explanation   string `protobuf:"bytes,3,opt,name=explanation,proto3" json:"explanation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyObjectResponse) Reset() {
	*x = ClassifyObjectResponse{}
	mi := &file_classification_v1_classification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyObjectResponse) ProtoMessage() {}

func (x *ClassifyObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_classification_v1_classification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyObjectResponse.ProtoReflect.Descriptor instead.
func (*ClassifyObjectResponse) Descriptor() ([]byte, []int) {
	return file_classification_v1_classification_proto_rawDescGZIP(), []int{1}
}

func (x *ClassifyObjectResponse) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *ClassifyObjectResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ClassifyObjectResponse) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

var File_classification_v1_classification_proto protoreflect.FileDescriptor

const file_classification_v1_classification_proto_rawDesc = "" +
	"\n" +
	"&classification/v1/classification.proto\x12\x11classification.v1\"z\n" +
	"\x15ClassifyObjectRequest\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x14\n" +
	"\x05color\x18\x02 \x01(\tR\x05color\x12)\n" +
	"\x10duration_seconds\x18\x03 \x01(\x05R\x0fdurationSeconds\"{\n" +
	"\x16ClassifyObjectResponse\x12\x1f\n" +
	"\vobject_type\x18\x01 \x01(\tR\n" +
	"objectType\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12 \n" +
	"\vexplanation\x18\x03 \x01(\tR\vexplanation2~\n" +
	"\x15ClassificationService\x12e\n" +
	"\x0eClassifyObject\x12(.classification.v1.ClassifyObjectRequest\x1a).classification.v1.ClassifyObjectResponseBfZdgithub.com/mbakhodurov/homeworks2/week7/tracing/shared/pkg/proto/classification/v1;classification_v1b\x06proto3"

var (
	file_classification_v1_classification_proto_rawDescOnce sync.Once
	file_classification_v1_classification_proto_rawDescData []byte
)

func file_classification_v1_classification_proto_rawDescGZIP() []byte {
	file_classification_v1_classification_proto_rawDescOnce.Do(func() {
		file_classification_v1_classification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_classification_v1_classification_proto_rawDesc), len(file_classification_v1_classification_proto_rawDesc)))
	})
	return file_classification_v1_classification_proto_rawDescData
}

var file_classification_v1_classification_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_classification_v1_classification_proto_goTypes = []any{
	(*ClassifyObjectRequest)(nil),  // 0: classification.v1.ClassifyObjectRequest
	(*ClassifyObjectResponse)(nil), // 1: classification.v1.ClassifyObjectResponse
}
var file_classification_v1_classification_proto_depIdxs = []int32{
	0, // 0: classification.v1.ClassificationService.ClassifyObject:input_type -> classification.v1.ClassifyObjectRequest
	1, // 1: classification.v1.ClassificationService.ClassifyObject:output_type -> classification.v1.ClassifyObjectResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_classification_v1_classification_proto_init() }
func file_classification_v1_classification_proto_init() {
	if File_classification_v1_classification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_classification_v1_classification_proto_rawDesc), len(file_classification_v1_classification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_classification_v1_classification_proto_goTypes,
		DependencyIndexes: file_classification_v1_classification_proto_depIdxs,
		MessageInfos:      file_classification_v1_classification_proto_msgTypes,
	}.Build()
	File_classification_v1_classification_proto = out.File
	file_classification_v1_classification_proto_goTypes = nil
	file_classification_v1_classification_proto_depIdxs = nil
}
