// Code generated by ogen, DO NOT EDIT.

package weatherv1

import (
	"time"
)

// Ref: #
type Error struct {
	// HTTP-код ошибки.
	Code int `json:"code"`
	// Человекочитаемое описание ошибки.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

type GetWeatherByCityBadRequest Error

func (*GetWeatherByCityBadRequest) getWeatherByCityRes() {}

type GetWeatherByCityInternalServerError Error

func (*GetWeatherByCityInternalServerError) getWeatherByCityRes() {}

type GetWeatherByCityNotFound Error

func (*GetWeatherByCityNotFound) getWeatherByCityRes() {}

type UpdateWeatherByCityBadRequest Error

func (*UpdateWeatherByCityBadRequest) updateWeatherByCityRes() {}

type UpdateWeatherByCityInternalServerError Error

func (*UpdateWeatherByCityInternalServerError) updateWeatherByCityRes() {}

// Ref: #
type UpdateWeatherRequest struct {
	// Температура в градусах Цельсия.
	Temperature float64 `json:"temperature"`
}

// GetTemperature returns the value of Temperature.
func (s *UpdateWeatherRequest) GetTemperature() float64 {
	return s.Temperature
}

// SetTemperature sets the value of Temperature.
func (s *UpdateWeatherRequest) SetTemperature(val float64) {
	s.Temperature = val
}

// Ref: #
type Weather struct {
	// Название города.
	City string `json:"city"`
	// Температура в градусах Цельсия.
	Temperature float64 `json:"temperature"`
	// Время последнего обновления данных (ISO 8601).
	UpdatedAt time.Time `json:"updated_at"`
}

// GetCity returns the value of City.
func (s *Weather) GetCity() string {
	return s.City
}

// GetTemperature returns the value of Temperature.
func (s *Weather) GetTemperature() float64 {
	return s.Temperature
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Weather) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetCity sets the value of City.
func (s *Weather) SetCity(val string) {
	s.City = val
}

// SetTemperature sets the value of Temperature.
func (s *Weather) SetTemperature(val float64) {
	s.Temperature = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Weather) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

func (*Weather) getWeatherByCityRes()    {}
func (*Weather) updateWeatherByCityRes() {}
