// Code generated by ogen, DO NOT EDIT.

package weatherv1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetWeatherByCity implements GetWeatherByCity operation.
//
// Возвращает текущие данные о погоде для указанного
// города.
//
// GET /api/v1/weather/{city}
func (UnimplementedHandler) GetWeatherByCity(ctx context.Context, params GetWeatherByCityParams) (r GetWeatherByCityRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateWeatherByCity implements UpdateWeatherByCity operation.
//
// Обновляет или создаёт данные о погоде для указанного
// города.
//
// PUT /api/v1/weather/{city}
func (UnimplementedHandler) UpdateWeatherByCity(ctx context.Context, req *UpdateWeatherRequest, params UpdateWeatherByCityParams) (r UpdateWeatherByCityRes, _ error) {
	return r, ht.ErrNotImplemented
}
